# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/D_File/FPGAprj/shousiACC/cnn_vivado_2018/cnn_vivado_2018.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_4/design_1_axi_smc_4.xci
# IP: The module: 'design_1_axi_smc_4' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/D_File/FPGAprj/shousiACC/cnn_vivado_2018/cnn_vivado_2018.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/bd_6cc2.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/D_File/FPGAprj/shousiACC/cnn_vivado_2018/cnn_vivado_2018.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_0/bd_6cc2_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/D_File/FPGAprj/shousiACC/cnn_vivado_2018/cnn_vivado_2018.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_1/bd_6cc2_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/D_File/FPGAprj/shousiACC/cnn_vivado_2018/cnn_vivado_2018.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_2/bd_6cc2_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/D_File/FPGAprj/shousiACC/cnn_vivado_2018/cnn_vivado_2018.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_3/bd_6cc2_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/D_File/FPGAprj/shousiACC/cnn_vivado_2018/cnn_vivado_2018.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_4/bd_6cc2_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/D_File/FPGAprj/shousiACC/cnn_vivado_2018/cnn_vivado_2018.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_5/bd_6cc2_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/D_File/FPGAprj/shousiACC/cnn_vivado_2018/cnn_vivado_2018.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_6/bd_6cc2_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/D_File/FPGAprj/shousiACC/cnn_vivado_2018/cnn_vivado_2018.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_7/bd_6cc2_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/D_File/FPGAprj/shousiACC/cnn_vivado_2018/cnn_vivado_2018.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_8/bd_6cc2_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/D_File/FPGAprj/shousiACC/cnn_vivado_2018/cnn_vivado_2018.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_9/bd_6cc2_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/D_File/FPGAprj/shousiACC/cnn_vivado_2018/cnn_vivado_2018.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_10/bd_6cc2_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/D_File/FPGAprj/shousiACC/cnn_vivado_2018/cnn_vivado_2018.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_11/bd_6cc2_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/D_File/FPGAprj/shousiACC/cnn_vivado_2018/cnn_vivado_2018.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_12/bd_6cc2_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/D_File/FPGAprj/shousiACC/cnn_vivado_2018/cnn_vivado_2018.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_1/bd_6cc2_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/D_File/FPGAprj/shousiACC/cnn_vivado_2018/cnn_vivado_2018.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_1/bd_6cc2_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/D_File/FPGAprj/shousiACC/cnn_vivado_2018/cnn_vivado_2018.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_5/bd_6cc2_s00a2s_0_ooc.xdc

# XDC: c:/D_File/FPGAprj/shousiACC/cnn_vivado_2018/cnn_vivado_2018.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_6/bd_6cc2_sarn_0_ooc.xdc

# XDC: c:/D_File/FPGAprj/shousiACC/cnn_vivado_2018/cnn_vivado_2018.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_7/bd_6cc2_srn_0_ooc.xdc

# XDC: c:/D_File/FPGAprj/shousiACC/cnn_vivado_2018/cnn_vivado_2018.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_8/bd_6cc2_sawn_0_ooc.xdc

# XDC: c:/D_File/FPGAprj/shousiACC/cnn_vivado_2018/cnn_vivado_2018.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_9/bd_6cc2_swn_0_ooc.xdc

# XDC: c:/D_File/FPGAprj/shousiACC/cnn_vivado_2018/cnn_vivado_2018.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_10/bd_6cc2_sbn_0_ooc.xdc

# XDC: c:/D_File/FPGAprj/shousiACC/cnn_vivado_2018/cnn_vivado_2018.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_11/bd_6cc2_m00s2a_0_ooc.xdc

# XDC: c:/D_File/FPGAprj/shousiACC/cnn_vivado_2018/cnn_vivado_2018.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_4/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_smc_4'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/D_File/FPGAprj/shousiACC/cnn_vivado_2018/cnn_vivado_2018.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_4/design_1_axi_smc_4.xci
# IP: The module: 'design_1_axi_smc_4' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/D_File/FPGAprj/shousiACC/cnn_vivado_2018/cnn_vivado_2018.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/bd_6cc2.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/D_File/FPGAprj/shousiACC/cnn_vivado_2018/cnn_vivado_2018.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_0/bd_6cc2_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/D_File/FPGAprj/shousiACC/cnn_vivado_2018/cnn_vivado_2018.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_1/bd_6cc2_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/D_File/FPGAprj/shousiACC/cnn_vivado_2018/cnn_vivado_2018.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_2/bd_6cc2_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/D_File/FPGAprj/shousiACC/cnn_vivado_2018/cnn_vivado_2018.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_3/bd_6cc2_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/D_File/FPGAprj/shousiACC/cnn_vivado_2018/cnn_vivado_2018.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_4/bd_6cc2_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/D_File/FPGAprj/shousiACC/cnn_vivado_2018/cnn_vivado_2018.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_5/bd_6cc2_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/D_File/FPGAprj/shousiACC/cnn_vivado_2018/cnn_vivado_2018.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_6/bd_6cc2_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/D_File/FPGAprj/shousiACC/cnn_vivado_2018/cnn_vivado_2018.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_7/bd_6cc2_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/D_File/FPGAprj/shousiACC/cnn_vivado_2018/cnn_vivado_2018.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_8/bd_6cc2_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/D_File/FPGAprj/shousiACC/cnn_vivado_2018/cnn_vivado_2018.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_9/bd_6cc2_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/D_File/FPGAprj/shousiACC/cnn_vivado_2018/cnn_vivado_2018.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_10/bd_6cc2_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/D_File/FPGAprj/shousiACC/cnn_vivado_2018/cnn_vivado_2018.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_11/bd_6cc2_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/D_File/FPGAprj/shousiACC/cnn_vivado_2018/cnn_vivado_2018.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_12/bd_6cc2_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/D_File/FPGAprj/shousiACC/cnn_vivado_2018/cnn_vivado_2018.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_1/bd_6cc2_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/D_File/FPGAprj/shousiACC/cnn_vivado_2018/cnn_vivado_2018.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_1/bd_6cc2_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/D_File/FPGAprj/shousiACC/cnn_vivado_2018/cnn_vivado_2018.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_5/bd_6cc2_s00a2s_0_ooc.xdc

# XDC: c:/D_File/FPGAprj/shousiACC/cnn_vivado_2018/cnn_vivado_2018.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_6/bd_6cc2_sarn_0_ooc.xdc

# XDC: c:/D_File/FPGAprj/shousiACC/cnn_vivado_2018/cnn_vivado_2018.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_7/bd_6cc2_srn_0_ooc.xdc

# XDC: c:/D_File/FPGAprj/shousiACC/cnn_vivado_2018/cnn_vivado_2018.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_8/bd_6cc2_sawn_0_ooc.xdc

# XDC: c:/D_File/FPGAprj/shousiACC/cnn_vivado_2018/cnn_vivado_2018.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_9/bd_6cc2_swn_0_ooc.xdc

# XDC: c:/D_File/FPGAprj/shousiACC/cnn_vivado_2018/cnn_vivado_2018.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_10/bd_6cc2_sbn_0_ooc.xdc

# XDC: c:/D_File/FPGAprj/shousiACC/cnn_vivado_2018/cnn_vivado_2018.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_4/bd_0/ip/ip_11/bd_6cc2_m00s2a_0_ooc.xdc

# XDC: c:/D_File/FPGAprj/shousiACC/cnn_vivado_2018/cnn_vivado_2018.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_4/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_smc_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
